# Generated by Django 4.2.8 on 2024-10-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('tranaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=100)),
            ],
        ),
    ]
